services:
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - data-volume:/var/lib/mysql
      
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    env_file:
    - ./.env
    depends_on:
    - mysql
    volumes:
      - ./apps/api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
    - '3000:3000'
    
  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    volumes:
      - ./apps/client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5173:80'

 
volumes:
  data-volume:
    driver: local
