services:
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - data-volume:/var/lib/mysql
      
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    env_file:
    - ./.env
    depends_on:
    - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
    - '3000:3000'
 
volumes:
  data-volume:
    driver: local
